In [3]:
import numpy as np

### Broadcasting

In [17]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[4, 5, 6], [7, 8, 9]])

arr_2d_transposed = arr_2d.T
result = arr_1d[:, np.newaxis] + arr_2d_transposed

result

array([[ 5,  8],
       [ 7, 10],
       [ 9, 12]])

### Advanced Indexing

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([0, 1, 2])
print(arr[row_indices, col_indices])

bool_arr = arr > 5
print(arr[bool_arr])


[1 5 9]
[6 7 8 9]


### Vectorized Functions

In [6]:
arr = np.array([1, 2, 3, 4, 5])
result = np.sqrt(arr)
result

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

### Performance

In [7]:
import time

start_time = time.time()
# NumPy operation
arr = np.arange(1000000)
result = np.sum(arr)
end_time = time.time()
print("Time taken for NumPy operation:", end_time - start_time, "seconds")

start_time = time.time()
# Equivalent Python operation
result = sum(range(1000000))
end_time = time.time()
print("Time taken for Python operation:", end_time - start_time, "seconds")


Time taken for NumPy operation: 0.004705905914306641 seconds
Time taken for Python operation: 0.03411674499511719 seconds


### Memory Views

In [8]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1.view()
arr2

array([1, 2, 3, 4, 5])

### Linear Algebra

In [9]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues

array([-0.37228132,  5.37228132])

### FFT (Fast Fourier Transform)

In [10]:
signal = np.array([0, 1, 2, 1, 0])
fft_result = np.fft.fft(signal)

fft_result

array([ 4.        +0.j        , -2.11803399-1.53884177j,
        0.11803399+0.36327126j,  0.11803399-0.36327126j,
       -2.11803399+1.53884177j])

### Polynomial Operations

In [11]:
poly1 = np.poly1d([1, 2, 3])  # Represents polynomial 1 + 2*x + 3*x^2
poly2 = np.poly1d([4, 5, 6])  # Represents polynomial 4 + 5*x + 6*x^2
poly_sum = np.polyadd(poly1, poly2)  # Adds two polynomials
poly_product = np.polymul(poly1, poly2)  # Multiplies two polynomials
value = np.polyval(poly1, 2)  # Evaluates polynomial at x=2

value

11

### Interpolation

In [12]:
x = np.linspace(0, 10, 10)  # Sample x-values
y = np.sin(x)  # Sample y-values
interp_func = np.poly1d(np.polyfit(x, y, 3))  # Interpolates a polynomial of degree 3
interpolated_values = interp_func(np.linspace(0, 10, 100))  # Interpolated y-values

interpolated_values

array([ 6.38734818e-01,  5.88628335e-01,  5.40692185e-01,  4.94886426e-01,
        4.51171117e-01,  4.09506315e-01,  3.69852079e-01,  3.32168468e-01,
        2.96415539e-01,  2.62553352e-01,  2.30541964e-01,  2.00341434e-01,
        1.71911820e-01,  1.45213181e-01,  1.20205575e-01,  9.68490597e-02,
        7.51036943e-02,  5.49295368e-02,  3.62866457e-02,  1.91350793e-02,
        3.43489587e-03, -1.08538462e-02, -2.37710885e-02, -3.53567727e-02,
       -4.56508404e-02, -5.46932334e-02, -6.25238932e-02, -6.91827616e-02,
       -7.47097800e-02, -7.91448903e-02, -8.25280341e-02, -8.48991529e-02,
       -8.62981884e-02, -8.67650824e-02, -8.63397764e-02, -8.50622120e-02,
       -8.29723311e-02, -8.01100750e-02, -7.65153857e-02, -7.22282045e-02,
       -6.72884733e-02, -6.17361337e-02, -5.56111273e-02, -4.89533958e-02,
       -4.18028808e-02, -3.41995239e-02, -2.61832669e-02, -1.77940513e-02,
       -9.07181877e-03, -5.65110314e-05,  9.21193031e-03,  1.86935636e-02,
        2.83484472e-02,  

### Masked Arrays

In [13]:
data = np.array([1, 2, -999, 4, 5])
mask = data == -999  # Create a boolean mask for invalid values
masked_data = np.ma.masked_array(data, mask=mask)  # Create a masked array

masked_data

masked_array(data=[1, 2, --, 4, 5],
             mask=[False, False,  True, False, False],
       fill_value=999999)

### Broadcasting with Iterators

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x, row in np.nditer([arr, arr]):
    print(x, row)


1 1
2 2
3 3
4 4
5 5
6 6


### Custom Data Types

In [15]:
dt = np.dtype([('name', 'S10'), ('age', 'i4'), ('height', 'f4')])
data = np.array([('Alice', 25, 5.6), ('Bob', 30, 6.0)], dtype=dt)

data

array([(b'Alice', 25, 5.6), (b'Bob', 30, 6. )],
      dtype=[('name', 'S10'), ('age', '<i4'), ('height', '<f4')])

### Parallel Computing

In [16]:
import dask.array as da

arr = da.random.random((10000, 10000), chunks=(1000, 1000))
result = (arr + arr.T).sum(axis=1).mean().compute()

result

10000.065613618279