In [10]:
import numpy as np

### Creating NumPy arrays

In [11]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

### Array Attributes

In [12]:
print("Shape of arr_2d:", arr_2d.shape)
print("Data type of arr_2d:", arr_2d.dtype)
print("Number of dimensions in arr_2d:", arr_2d.ndim)

Shape of arr_2d: (3, 3)
Data type of arr_2d: int64
Number of dimensions in arr_2d: 2


### Array Operations

In [13]:
result = arr_1d + 10
print("Result of adding 10 to arr_1d:", result)

result = arr_1d * 2
print("Result of multiplying arr_1d by 2:", result)

result = np.dot(arr_2d, arr_2d)
print("Matrix multiplication of arr_2d with itself:", result)


Result of adding 10 to arr_1d: [11 12 13 14 15]
Result of multiplying arr_1d by 2: [ 2  4  6  8 10]
Matrix multiplication of arr_2d with itself: [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


### Array Indexing and Slicing

In [14]:
print("First element of arr_1d:", arr_1d[0])
print("First 3 elements of arr_1d:", arr_1d[:3])

First element of arr_1d: 1
First 3 elements of arr_1d: [1 2 3]


### Array Functions

In [15]:
print("Sum of all elements in arr_1d:", np.sum(arr_1d))
print("Mean of all elements in arr_1d:", np.mean(arr_1d))
print("Maximum value in arr_1d:", np.max(arr_1d))
print("Minimum value in arr_1d:", np.min(arr_1d))
reshaped_arr = np.reshape(arr_1d, (5, 1))
print("Reshaped arr_1d:", reshaped_arr)

Sum of all elements in arr_1d: 15
Mean of all elements in arr_1d: 3.0
Maximum value in arr_1d: 5
Minimum value in arr_1d: 1
Reshaped arr_1d: [[1]
 [2]
 [3]
 [4]
 [5]]


### Random Number Generation

In [16]:
rand_int = np.random.randint(1, 100, size=(3, 3))
print("Random integer array:", rand_int)

rand_float = np.random.rand(3, 3)
print("Random float array:", rand_float)

Random integer array: [[90 89 77]
 [ 2 14 72]
 [15 96 54]]
Random float array: [[0.06428764 0.32715656 0.48356309]
 [0.4969634  0.54951269 0.78933989]
 [0.85611052 0.89955856 0.55318119]]
