In [15]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


### Creating NumPy arrays

In [16]:
arr_zeros = np.zeros((3, 3))  # Creates a 3x3 array filled with zeros
arr_ones = np.ones((2, 4))  # Creates a 2x4 array filled with ones
arr_identity = np.eye(3)  # Creates a 3x3 identity matrix
arr_range = np.arange(0, 10, 2)  # Creates an array from 0 to 10 (exclusive) with step 2
arr_linspace = np.linspace(0, 10, 5)  # Creates an array of 5 evenly spaced numbers between 0 and 10

### Array Concatenation and Splitting

In [17]:
arr_concat = np.concatenate((arr_1d, arr_1d))  # Concatenates two arrays
arr_split = np.split(arr_concat, 2)  # Splits the concatenated array into two equal parts

arr_split

[array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5])]

### Broadcasting

In [18]:
arr_broadcast = np.array([1, 2, 3])
broadcast_result = arr_broadcast + 5  # Broadcasting scalar to array

broadcast_result

array([6, 7, 8])

### Statistical Operations

In [19]:
mean_value = np.mean(arr_1d)  # Mean of array elements
std_deviation = np.std(arr_1d)  # Standard deviation of array elements

mean_value
std_deviation

1.4142135623730951

### Trigonometric Functions

In [20]:
sin_values = np.sin(arr_range)  # Computes sine of array elements
cos_values = np.cos(arr_range)  # Computes cosine of array elements

sin_values
cos_values

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003])

### Sorting

In [21]:
arr_to_sort = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(arr_to_sort)  # Returns a sorted copy of the array

sorted_arr

array([1, 2, 3, 4, 5])

### Linear Algebra

In [22]:
mat_a = np.array([[1, 2], [3, 4]])
mat_b = np.array([[5, 6], [7, 8]])
mat_product = np.matmul(mat_a, mat_b)  # Matrix multiplication
mat_inverse = np.linalg.inv(mat_a)  # Inverse of a matrix

mat_product
mat_inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Reshaping

In [23]:
arr_flattened = arr_2d.flatten()  # Flattens a 2D array to 1D
arr_reshaped = np.reshape(arr_1d, (5, 1))  # Reshapes a 1D array to 2D

arr_reshaped

array([[1],
       [2],
       [3],
       [4],
       [5]])

### Indexing with boolean arrays

In [24]:
bool_arr = np.array([True, False, True, False, True])
filtered_arr = arr_1d[bool_arr]  # Selects elements of arr_1d where bool_arr is True

filtered_arr

array([1, 3, 5])

### Finding Unique elements

In [25]:
unique_elements = np.unique(arr_to_sort)  # Returns the unique elements of an array

unique_elements

array([1, 2, 3, 4, 5])

### Saving and Loading Arrays

In [26]:
np.save('saved_array.npy', arr_1d)  # Saves an array to a binary file
loaded_array = np.load('saved_array.npy')  # Loads the saved array from file

loaded_array

array([1, 2, 3, 4, 5])

### Iterating over arrays

In [27]:
for x in np.nditer(arr_2d):
    print(x, end=' ')

1 2 3 4 5 6 7 8 9 